set_license("GPL-3.0")
add_rules("mode.debug", "mode.release")
add_requires("ffmpeg")
add_requires("eigen", "imgui")
set_languages("cxx20")
package("libwave")
    set_description("LIBWAVE")
    set_license("Mozilla Public License 2.0")
    add_deps("cmake")

    set_urls("https://github.com/brglng/libwave.git")
    add_versions("1.0.0", "1f255d332a1edf0dcd0bdad23b388a531396b58b")

    on_install(function (package)
        local configs = {}
        table.insert(configs, "-DCMAKE_BUILD_TYPE=" .. (package:debug() and "Debug" or "Release"))
        table.insert(configs, "-DBUILD_SHARED_LIBS=" .. (package:config("shared") and "ON" or "OFF"))
        import("package.tools.cmake").install(package, configs)
    end)
package_end()
add_requires("libwave")
target("rany")
    add_packages("ffmpeg", "imgui", "libwave")
    add_packages("eigen")
    set_kind("binary")
    add_files("src/*.cpp")